spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/bread2u
    username: sa
    password:
    driver-class-name: org.h2.Driver
    jackson.date-format: yyyy-MM-dd
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

#logging:
#  level:
#    root: debug